const list_products = [
  {
    productName: "SamSung Galaxy J4+",
    description: "Smartphone Samsung với màn hình 6.0', camera 13MP, pin 3300mAh",
    price: "3.490.000",
    category: "smartphone",
    brandName: "Samsung",
    img: ["img/products/samsung-galaxy-j4-plus-pink-400x400.jpg"],
  },
  {
    productName: "Xiaomi Mi 8 Lite",
    description: "Smartphone Xiaomi với màn hình 6.26', camera kép, pin 3300mAh",
    price: "6.690.000",
    category: "smartphone",
    brandName: "Xiaomi",
    img: ["img/products/xiaomi-mi-8-lite-black-1-600x600.jpg"],

  },
  {
    productName: "Oppo F9",
    description: "Smartphone Oppo với màn hình 6.3', camera selfie 25MP, sạc nhanh",
    price: "7.690.000",
    category: "smartphone",
    brandName: "Oppo",
    img: ["img/products/oppo-f9-red-600x600.jpg"],
  },
  {
    productName: "Nokia 5.1 Plus",
    description: "Smartphone Nokia với Android One, camera kép, thiết kế sang trọng",
    price: "4.790.000",
    category: "smartphone",
    brandName: "Nokia",
    img: ["img/products/nokia-51-plus-black-18thangbh-400x400.jpg"],
  },
  {
    productName: "Samsung Galaxy A8+ (2018)",
    description: "Smartphone cao cấp Samsung với màn hình Super AMOLED, 3 camera",
    price: "11.990.000",
    category: "smartphone",
    brandName: "Samsung",
    img: ["img/products/samsung-galaxy-a8-plus-2018-gold-600x600.jpg"],
  },
  {
    productName: "iPhone X 256GB Silver",
    description: "iPhone X bản 256GB màu bạc, màn hình OLED Super Retina",
    price: "31.990.000",
    category: "smartphone",
    brandName: "Apple",
    img: ["img/products/iphone-x-256gb-silver-400x400.jpg"],
  },
  {
    productName: "Oppo A3s 32GB",
    description: "Smartphone Oppo giá rẻ, pin khủng 4230mAh, màn hình lớn",
    price: "4.690.000",
    category: "smartphone",
    brandName: "Oppo",
    img: ["img/products/oppo-a3s-32gb-600x600.jpg"],
  },
  {
    productName: "Samsung Galaxy J8",
    description: "Smartphone Samsung với màn hình Super AMOLED, camera kép",
    price: "6.290.000",
    category: "smartphone",
    brandName: "Samsung",
    img: ["img/products/samsung-galaxy-j8-600x600-600x600.jpg"],
  },
  {
    productName: "iPad 2018 Wifi 32GB",
    description: "iPad 2018 bản Wifi 32GB, màn hình 9.7 inch, chip A10 Fusion",
    price: "8.990.000",
    category: "tablet",
    brandName: "Apple",
    img: ["img/products/ipad-wifi-32gb-2018-thumb-600x600.jpg"],
  },
  {
    productName: "iPhone 7 Plus 32GB",
    description: "iPhone 7 Plus bản 32GB, camera kép, chống nước",
    price: "17.000.000",
    category: "smartphone",
    brandName: "Apple",
    img: ["img/products/iphone-7-plus-32gb-hh-600x600.jpg"],
  },
  {
    productName: "Xiaomi Mi 8",
    description: "Flagship Xiaomi với thiết kế notch, camera kép, hiệu năng mạnh",
    price: "12.990.000",
    category: "smartphone",
    brandName: "Xiaomi",
    img: ["img/products/xiaomi-mi-8-1-600x600.jpg"],
  },
  {
    productName: "Mobiistar X",
    description: "Smartphone Mobiistar với camera selfie 16MP, giá rẻ",
    price: "3.490.000",
    category: "smartphone",
    brandName: "Mobiistar",
    img: ["img/products/mobiistar-x-3-600x600.jpg"],
  },
  {
    productName: "Mobiistar Zumbo S2 Dual",
    description: "Smartphone 2 SIM, camera selfie kép, thiết kế trẻ trung",
    price: "2.850.000",
    category: "smartphone",
    brandName: "Mobiistar",
    img: ["img/products/mobiistar-zumbo-s2-dual-300x300.jpg"],
  },
  {
    productName: "Mobiistar E Selfie",
    description: "Smartphone tập trung selfie với camera trước 13MP",
    price: "2.490.000",
    category: "smartphone",
    brandName: "Mobiistar",
    img: ["img/products/mobiistar-e-selfie-300-1copy-600x600.jpg"],
  },
  {
    productName: "Mobiistar B310",
    description: "Điện thoại phổ thông, pin lâu, bền bỉ",
    price: "260.000",
    category: "feature phone",
    brandName: "Mobiistar",
    img: ["img/products/mobiistar-b310-orange-600x600.jpg"],
  },
  {
    productName: "Xiaomi Redmi Note 5",
    description: "Smartphone pin trâu 4000mAh, camera kép, giá rẻ",
    price: "5.690.000",
    category: "smartphone",
    brandName: "Xiaomi",
    img: ["img/products/xiaomi-redmi-note-5-pro-600x600.jpg"],
  },
  {
    productName: "Xiaomi Redmi 5 Plus 4GB",
    description: "Smartphone màn hình tràn viền, pin khủng 4000mAh",
    price: "4.790.000",
    category: "smartphone",
    brandName: "Xiaomi",
    img: ["img/products/xiaomi-redmi-5-plus-600x600.jpg"],
  },
  {
    productName: "Huawei Mate 20 Pro",
    description: "Flagship Huawei với 3 camera Leica, màn hình OLED 2K+",
    price: "21.990.000",
    category: "smartphone",
    brandName: "Huawei",
    img: ["img/products/huawei-mate-20-pro-green-600x600.jpg"],
  },
  {
    productName: "Huawei Nova 3",
    description: "Smartphone selfie với camera trước kép, hiệu năng mạnh",
    price: "9.990.000",
    category: "smartphone",
    brandName: "Huawei",
    img: ["img/products/huawei-nova-3-2-600x600.jpg"],
  },
  {
    productName: "Huawei Y5 2017",
    description: "Smartphone giá rẻ, thiết kế nhỏ gọn, pin 3000mAh",
    price: "1.990.000",
    category: "smartphone",
    brandName: "Huawei",
    img: ["img/products/huawei-y5-2017-300x300.jpg"],
  },
  {
    productName: "Nokia black future",
    description: "Smartphone cao cấp với thiết kế độc đáo, cấu hình khủng",
    price: "999.999.000",
    category: "smartphone",
    brandName: "Nokia",
    img: ["https://cdn.tgdd.vn/Products/Images/42/22701/dien-thoai-di-dong-Nokia-1280-dienmay.com-l.jpg"],
  },
  {
    productName: "Samsung Galaxy A7 (2018)",
    description: "Smartphone Samsung với 3 camera sau, màn hình Infinity",
    price: "8.990.000",
    category: "smartphone",
    brandName: "Samsung",
    img: ["https://cdn.tgdd.vn/Products/Images/42/194327/samsung-galaxy-a7-2018-128gb-black-400x400.jpg"],
  },
  {
    productName: "Realme 2 Pro 8GB/128GB",
    description: "Smartphone cấu hình mạnh với RAM 8GB, bộ nhớ 128GB",
    price: "6.990.000",
    category: "smartphone",
    brandName: "Realme",
    img: ["https://cdn.tgdd.vn/Products/Images/42/192002/oppo-realme-2-pro-black-600x600.jpg"],
  },
  {
    productName: "Realme 2 4GB/64GB",
    description: "Smartphone giá rẻ, pin khủng 4230mAh, màn hình giọt nước",
    price: "4.490.000",
    category: "smartphone",
    brandName: "Realme",
    img: ["https://cdn.tgdd.vn/Products/Images/42/193462/realme-2-4gb-64gb-docquyen-600x600.jpg"],
  },
  {
    productName: "Realme C1",
    description: "Smartphone giá rẻ, pin trâu, phù hợp học sinh, sinh viên",
    price: "2.490.000",
    category: "smartphone",
    brandName: "Realme",
    img: ["https://cdn.tgdd.vn/Products/Images/42/193286/realme-c1-black-600x600.jpg"],
  },
  {
    productName: "Realme 2 Pro 4GB/64GB",
    description: "Smartphone hiệu năng tốt, camera 16MP, màn hình Full HD+",
    price: "5.590.000",
    category: "smartphone",
    brandName: "Realme",
    img: ["https://cdn.tgdd.vn/Products/Images/42/193464/realme-2-pro-4gb-64gb-blue-600x600.jpg"],
  },
  {
    productName: "Philips E331",
    description: "Điện thoại phổ thông bền bỉ, pin lâu, 2 SIM",
    price: "890.000",
    category: "feature phone",
    brandName: "Philips",
    img: ["https://cdn.tgdd.vn/Products/Images/42/139742/philips-e331-xenium-300-300x300.jpg"],
  },
  {
    productName: "Philips S329",
    description: "Smartphone giá rẻ, màn hình 5 inch, camera 13MP",
    price: "2.390.000",
    category: "smartphone",
    brandName: "Philips",
    img: ["https://cdn.tgdd.vn/Products/Images/42/143146/philips-s329-2-300x300.jpg"],
  },
  {
    productName: "Philips E103",
    description: "Điện thoại cơ bản, pin lâu, thiết kế nhỏ gọn",
    price: "260.000",
    category: "feature phone",
    brandName: "Philips",
    img: ["https://cdn.tgdd.vn/Products/Images/42/73727/philips-e103-9-300x300.jpg"],
  },
  {
    productName: "Vivo V11",
    description: "Smartphone selfie 25MP, màn hình Full HD+, vân tay trong màn hình",
    price: "10.990.000",
    category: "smartphone",
    brandName: "Vivo",
    img: ["https://cdn.tgdd.vn/Products/Images/42/188828/vivo-v11-600x600.jpg"],
  },
  {
    productName: "Vivo V9",
    description: "Smartphone selfie 24MP, màn hình tràn viền, thiết kế đẹp",
    price: "7.490.000",
    category: "smartphone",
    brandName: "Vivo",
    img: ["https://cdn.tgdd.vn/Products/Images/42/155047/vivo-v9-2-1-600x600-600x600.jpg"],
  },
  {
    productName: "Vivo Y85",
    description: "Smartphone giá rẻ, màn hình giọt nước, thiết kế trẻ trung",
    price: "4.990.000",
    category: "smartphone",
    brandName: "Vivo",
    img: ["https://cdn.tgdd.vn/Products/Images/42/156205/vivo-y85-red-docquyen-600x600.jpg"],
  },
  {
    productName: "Vivo Y71",
    description: "Smartphone giá rẻ, màn hình 6 inch, pin 3360mAh",
    price: "3.290.000",
    category: "smartphone",
    brandName: "Vivo",
    img: ["https://cdn.tgdd.vn/Products/Images/42/158585/vivo-y71-docquyen-600x600.jpg"],
  },
  {
    productName: "Mobell M789",
    description: "Điện thoại phổ thông, bàn phím cứng, bền bỉ",
    price: "550.000",
    category: "feature phone",
    brandName: "Mobell",
    img: ["https://cdn.tgdd.vn/Products/Images/42/92016/mobell-m789-8-300x300.jpg"],
  },
  {
    productName: "Mobell Rock 3",
    description: "Điện thoại pin trâu 5000mAh, bền bỉ với tiêu chuẩn quân đội",
    price: "590.000",
    category: "feature phone",
    brandName: "Mobell",
    img: ["https://cdn.tgdd.vn/Products/Images/42/112837/mobell-rock-3-2-300x300.jpg"],
  },
  {
    productName: "Mobell S60",
    description: "Smartphone giá rẻ, camera kép, thiết kế thời trang",
    price: "1.790.000",
    category: "smartphone",
    brandName: "Mobell",
    img: ["https://cdn.tgdd.vn/Products/Images/42/193271/mobell-s60-red-1-600x600.jpg"],
  },
  {
    productName: "Itel P32",
    description: "Smartphone giá rẻ, pin 4000mAh, màn hình 5.45 inch",
    price: "1.890.000",
    category: "smartphone",
    brandName: "Itel",
    img: ["https://cdn.tgdd.vn/Products/Images/42/186851/itel-p32-gold-600x600.jpg"],
  },
  {
    productName: "Itel A32F",
    description: "Smartphone Android Go, thiết kế nhỏ gọn, giá rẻ",
    price: "1.350.000",
    category: "smartphone",
    brandName: "Itel",
    img: ["https://cdn.tgdd.vn/Products/Images/42/193990/itel-a32f-pink-gold-600x600.jpg"],
  },
  {
    productName: "Itel it2123",
    description: "Điện thoại phổ thông, pin lâu, giá rẻ",
    price: "160.000",
    category: "feature phone",
    brandName: "Itel",
    img: ["https://cdn.tgdd.vn/Products/Images/42/146651/itel-it2123-d-300-300x300.jpg"],
  },
  {
    productName: "Itel it2161",
    description: "Điện thoại phổ thông 2 SIM, pin lâu, bền bỉ",
    price: "170.000",
    category: "feature phone",
    brandName: "Itel",
    img: ["https://cdn.tgdd.vn/Products/Images/42/193989/itel-it2161-600x600.jpg"],
  },
  {
    productName: "Coolpad N3D",
    description: "Smartphone giá rẻ, màn hình 5.45 inch, camera kép",
    price: "2.390.000",
    category: "smartphone",
    brandName: "Coolpad",
    img: ["https://cdn.tgdd.vn/Products/Images/42/193504/coolpad-n3d-blue-600x600.jpg"],
  },
  {
    productName: "Coolpad N3",
    description: "Smartphone Android Go, giá rẻ, phù hợp người mới dùng",
    price: "1.890.000",
    category: "smartphone",
    brandName: "Coolpad",
    img: ["https://cdn.tgdd.vn/Products/Images/42/193502/coolpad-n3-gray-1-600x600.jpg"],
  },
  {
    productName: "Coolpad N3 mini",
    description: "Smartphone nhỏ gọn, giá rẻ, phù hợp người già, trẻ em",
    price: "1.390.000",
    category: "smartphone",
    brandName: "Coolpad",
    img: ["https://cdn.tgdd.vn/Products/Images/42/193503/coolpad-n3-mini-600x600.jpg"],
  },
  {
    productName: "HTC U12 life",
    description: "Smartphone HTC với thiết kế sang trọng, camera kép",
    price: "7.690.000",
    category: "smartphone",
    brandName: "HTC",
    img: ["https://cdn.tgdd.vn/Products/Images/42/186397/htc-u12-life-1-600x600.jpg"],
  },
  {
    productName: "Motorola Moto C 4G",
    description: "Smartphone giá rẻ, hỗ trợ 4G, thiết kế nhỏ gọn",
    price: "1.290.000",
    category: "smartphone",
    brandName: "Motorola",
    img: ["https://cdn.tgdd.vn/Products/Images/42/109099/motorola-moto-c-4g-300-300x300.jpg"],
  },
  {
    productName: "iPhone Xr 128GB",
    description: "iPhone Xr bản 128GB, màn hình Liquid Retina, chip A12 Bionic",
    price: "24.990.000",
    category: "smartphone",
    brandName: "Apple",
    img: ["https://cdn.tgdd.vn/Products/Images/42/191483/iphone-xr-128gb-red-600x600.jpg"],
  },
  {
    productName: "iPhone 8 Plus 64GB",
    description: "iPhone 8 Plus bản 64GB, camera kép, hỗ trợ sạc nhanh",
    price: "20.990.000",
    category: "smartphone",
    brandName: "Apple",
    img: ["https://cdn.tgdd.vn/Products/Images/42/114110/iphone-8-plus-hh-600x600.jpg"],
  },
  {
    productName: "iPhone 8 Plus 256GB",
    description: "iPhone 8 Plus bản 256GB, bộ nhớ lớn, hiệu năng mạnh",
    price: "25.790.000",
    category: "smartphone",
    brandName: "Apple",
    img: ["https://cdn.tgdd.vn/Products/Images/42/114114/iphone-8-plus-256gb-red-600x600.jpg"],
  },
  {
    productName: "iPhone Xr 64GB",
    description: "iPhone Xr bản 64GB, nhiều màu sắc, hiệu năng mạnh mẽ",
    price: "22.990.000",
    category: "smartphone",
    brandName: "Apple",
    img: ["https://cdn.tgdd.vn/Products/Images/42/190325/iphone-xr-black-400x460.png"],
  },
  {
    productName: "Huawei Nova 2i",
    description: "Smartphone selfie với camera trước kép, màn hình Full HD+",
    price: "4.490.000",
    category: "smartphone",
    brandName: "Huawei",
    img: ["https://cdn.tgdd.vn/Products/Images/42/157031/samsung-galaxy-a6-2018-2-600x600.jpg"],
  }
];

module.exports = list_products;